### PR TITLE
Fix failure for optimizer_function

### PR DESCRIPTION
**Pull request by macroyuyang**
Fix failure by non-proper has_oids value when executing nodeSplitUpdate when optimizer=on. 
has_oids is different between nodes across Motion, so that receiver motion cannot retrieve correct value from sender motion.

The failure could be reproduced by:

optimizer=on. The failure could be reproduced by:
set optimizer=on;
DROP TABLE IF EXISTS dml_heap_r;
DROP TABLE IF EXISTS dml_heap_p;

CREATE TABLE dml_heap_r (col1 serial,a int , b int default -1, c text) WITH OIDS DISTRIBUTED BY (a);
CREATE TABLE dml_heap_p (col1 serial, a numeric, b decimal) WITH OIDS DISTRIBUTED BY (a,b);

INSERT INTO dml_heap_p(a,b) SELECT id as a, id as b FROM (SELECT * FROM generate_series(1,2) as id) AS x;
INSERT INTO dml_heap_p(a,b) VALUES(NULL,NULL);

INSERT INTO dml_heap_r(a,b,c) VALUES(generate_series(1,2),generate_series(1,2),'r');
INSERT INTO dml_heap_r(a,b,c) VALUES(NULL,NULL,NULL);

SELECT COUNT(*) FROM dml_heap_r;
SELECT COUNT(*) FROM dml_heap_p;
SELECT SUM(a) FROM dml_heap_r;

DROP TABLE IF EXISTS tempoid;
CREATE TABLE tempoid as SELECT oid,col1,a FROM dml_heap_r ORDER BY 1;

SELECT SUM(dml_heap_r.a) FROM dml_heap_p, dml_heap_r WHERE dml_heap_r.b = dml_heap_p.a;

UPDATE dml_heap_r SET a = dml_heap_r.a FROM dml_heap_p WHERE dml_heap_r.b = dml_heap_p.a;

### CODE REVIEW

**Comment by hlinnaka** [comment]
Cool, +1. I'm curious what changed, i.e. shy did it work before? But the new code sure looks more correct.
- Heikki

**Comment by vraghavan78** [comment]
@hlinnaka as @dhanashreek89 and I mentioned in https://github.com/greenplum-db/gpdb/issues/3611 this never worked before.

**Comment by bhuvnesh2703** [comment]
@macroyuyang could we add a test case for it?

**Comment by vraghavan78** [comment]
There are tests already on master. They just need to be enable (see FIXME)

https://github.com/greenplum-db/gpdb/blob/7c18e3f7d9877556cdefcfe424eb74d8ae2b44e4/src/test/regress/sql/qp_dml_oids.sql

**Comment by bhuvnesh2703** [comment]
thanks @vraghavan78 for pointing it out.

**Comment by dhanashreek89** [comment]
Thanks @macroyuyang for fixing this!  
The issue exists on gpdb master, 5X_STABLE and 4.3_STABLE as well and we verified that this patch fixes it in all versions.

So is it OK if we (QP team) take this over and merge in master and back-port all the way to 4.3_STABLE ?

**Comment by macroyuyang** [comment]
@dhanashreek89 Sure. Thank you for taking this over

**Comment by dhanashreek89** [comment]
> @dhanashreek89 Sure. Thank you for taking this over

Merged in master via https://github.com/greenplum-db/gpdb/commit/9f3d490357835bb2479b4e3f28e39645bed0a503
Thanks.

**Comment by hlinnaka** [comment]
We have the fix from `master` now, closing

**Pull request closed without merging**
