### PR TITLE
`EXECUTE ON [MASTER | ANY | ALL SEGMENTS]` for foreign tables

### PR DESCRIPTION
**Pull request by adam8157**
Please checkout each commit message and cases.

### CODE REVIEW

**Comment by adam8157** [comment]
Without this, FDW only runs on the master for now.

**Review by danielgustafsson — COMMENTED** [review]
I don't see a better way to MPPify the FDW interface than to specify the execution location, I do however think we wan't to avoid new syntax as much as possible and instead use the OPTIONS for this.

**Comment by mkiyama** [comment]
FYI- This seems to be a GPDB-dev thread associated with the PR.
https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/ZYYgUxkU1no

**Comment by adam8157** [comment]
The alternative way, using option: #43, please take a look.

**Comment by adam8157** [comment]
Moved to main repo since 9.2 merging is finished there.
https://github.com/greenplum-db/gpdb/pull/5411

**Pull request closed without merging**
