### PR TITLE
Merge TCL into PostgreSQL 9.2

### PR DESCRIPTION
**Pull request by HaozhouWang**
1. Add init file
2. Fix conflicts
3. Update tests case as some features are not supported in GPDB

### CODE REVIEW

**Comment by Eulerizeit** [comment]
I'm not opposed to this but does anyone want it?

Rob

**Comment by danielgustafsson** [comment]
> On 29 Jun 2018, at 13:24, Robert Eckhardt <notifications@github.com> wrote:
> 
> I'm not opposed to this but does anyone want it?

Probably not, but having it will lead to fewer merge conflicts and not having it will make little to no difference in maintenance.

**Comment by Eulerizeit** [comment]
On Fri, Jun 29, 2018 at 12:56 PM, Daniel Gustafsson <
notifications@github.com> wrote:

> > On 29 Jun 2018, at 13:24, Robert Eckhardt <notifications@github.com>
> wrote:
> >
> > I'm not opposed to this but does anyone want it?
>
> Probably not, but having it will lead to fewer merge conflicts and not
> having it will make little to no difference in maintenance.


So yes, the merge team wants it to make their lives easier. I 100% support
this.

-- Rob

**Comment by HaozhouWang** [comment]
Thanks @Eulerizeit , this PR is mainly for reducing the conflicts and help next merge a little easier.

**Review by zhangh43 — APPROVED** [review]

**Pull request merged**
